// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Error } from "./Error";
import type { Notif } from "./Notif";
import type { Resp } from "./Resp";

export type From = { "Resp": { id: number, resp: Resp, } } | { "Error": { id: number, err: Error, } } | { "Notif": { notif: Notif, } };
