// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LoginRequest } from "./LoginRequest";
import type { Session } from "./Session";
import type { SignRequest } from "./SignRequest";
import type { Wallet } from "./Wallet";

export type LoginResp = { sessions: Array<Session>, login_requests: Array<LoginRequest>, sign_requests: Array<SignRequest>, wallets: Array<Wallet>, };
