// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LoginRequestStatus } from "./LoginRequestStatus";

export type LoginRequest = { request_id: string, status: LoginRequestStatus, client_data: string | null, expires_at: number, };
