// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LoginRequestUpdatedNotif } from "./LoginRequestUpdatedNotif";
import type { SessionCreatedNotif } from "./SessionCreatedNotif";
import type { SessionRemovedNotif } from "./SessionRemovedNotif";
import type { SignRequestUpdatedNotif } from "./SignRequestUpdatedNotif";
import type { WalletUpdatedNotif } from "./WalletUpdatedNotif";

export type Notif = { "SessionCreated": SessionCreatedNotif } | { "SessionRemoved": SessionRemovedNotif } | { "LoginRequestUpdated": LoginRequestUpdatedNotif } | { "SignRequestUpdated": SignRequestUpdatedNotif } | { "WalletUpdated": WalletUpdatedNotif };
