// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LoginReq } from "./LoginReq";
import type { ServerActionReq } from "./ServerActionReq";
import type { StartLoginReq } from "./StartLoginReq";
import type { StartSignReq } from "./StartSignReq";

export type Req = { "Login": LoginReq } | { "StartLogin": StartLoginReq } | { "StartSign": StartSignReq } | { "ServerAction": ServerActionReq };
