// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LoginResp } from "./LoginResp";
import type { ServerActionResp } from "./ServerActionResp";
import type { StartLoginResp } from "./StartLoginResp";
import type { StartSignResp } from "./StartSignResp";

export type Resp = { "Login": LoginResp } | { "StartLogin": StartLoginResp } | { "StartSign": StartSignResp } | { "ServerAction": ServerActionResp };
