// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Session = { session_id: string, request_id: string, client_data: string | null, wallet_id: string, 
/**
 * Experimental. Only set on testnet for now.
 */
__descriptor: string | null, };
