// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SignRequestStatus } from "./SignRequestStatus";

export type SignRequest = { request_id: string, status: SignRequestStatus, client_data: string | null, expires_at: number, };
