// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LoginRequest } from "./LoginRequest";

export type StartLoginResp = { login_request: LoginRequest, };
