// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StartSignReq = { session_id: string, pset: string, client_data: string | null, ttl: number, };
