// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Utxo = { txid: string, vout: number, asset: string, asset_bf: string, value: bigint, value_bf: string, script_pubkey: string, };
