// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Utxo } from "./Utxo";

export type Wallet = { wallet_id: string, utxos: Array<Utxo>, recv_address: string, change_address: string, };
