// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Wallet } from "./Wallet";

export type WalletUpdatedNotif = { wallet: Wallet, };
